/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mta.oo17_io;

/**
 *
 * @author MB-teacher
 */
public class OpenWeatherJFrame extends javax.swing.JFrame {

    /**
     * Creates new form OpenWeatherJFrame
     */
    public OpenWeatherJFrame() {
        initComponents();
        buttonGroup1.add(cn1);
        buttonGroup1.add(cn2);
        buttonGroup1.add(cn3);
        buttonGroup1.add(cn4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cn1 = new javax.swing.JRadioButton();
        cn2 = new javax.swing.JRadioButton();
        cn3 = new javax.swing.JRadioButton();
        cn4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OpenWeather 現在天氣");

        cn1.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        cn1.setText("台北");

        cn2.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        cn2.setText("桃園");

        cn3.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        cn3.setText("台中");

        cn4.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        cn4.setText("高雄");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(cn1)
                .addGap(18, 18, 18)
                .addComponent(cn2)
                .addGap(18, 18, 18)
                .addComponent(cn3)
                .addGap(18, 18, 18)
                .addComponent(cn4)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cn1)
                    .addComponent(cn2)
                    .addComponent(cn3)
                    .addComponent(cn4))
                .addContainerGap(280, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpenWeatherJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpenWeatherJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpenWeatherJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpenWeatherJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpenWeatherJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cn1;
    private javax.swing.JRadioButton cn2;
    private javax.swing.JRadioButton cn3;
    private javax.swing.JRadioButton cn4;
    // End of variables declaration//GEN-END:variables
}
